#! /usr/bin/env bash
eval "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

BUSH_URL=${BUSH_URL:-https://raw.githubusercontent.com/xko/bush/mac/.bush}
eval "$(curl -fsSL "$BUSH_URL/lib")"

eval "$($HOMEBREW_PREFIX/bin/brew shellenv)"

b.say  "Install the default dependencies:"
b.run? "curl -fsSL \""$BUSH_URL/Brewfile"\" | brew bundle -q --file=- --no-lock"

b.say  "Permanently add brew to the path:"
b.run? "sudo sed -i.old '1s;^;$HOMEBREW_PREFIX/bin\n;' /etc/paths"

finger "$USER" | grep "$HOMEBREW_PREFIX/bin/bash" >/dev/null || {
    b.say  "Add brew-installed bash to allowed shells:"
    b.run? echo "$HOMEBREW_PREFIX/bin/bash" \| sudo tee -a /etc/shells
    b.say  "Set brew-installed bash as default:"
    b.run? chsh -s "$HOMEBREW_PREFIX/bin/bash"
}

b.run? "cd $HOME ; git init"
b.painterr

git remote | grep -e "^bush$" >/dev/null || {
    b.say

} exec_v git remote add -f bush https://github.com/xko/bush
exec_v git merge bush/mac

exec_v brew install --cask iterm2
