#! /usr/bin/env bash
eval "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
execute_sudo bash -c "printf '%s\n%s\n' \"$HOMEBREW_PREFIX/bin\" \"\$(cat /etc/paths)\" > /etc/paths"

eval "$($HOMEBREW_PREFIX/bin/brew shellenv)"
curl -fsSL https://raw.githubusercontent.com/xko/bush/mac/.bush/Brewfile | brew bundle -q --file=- --no-lock

execute_sudo bash -c "echo $HOMEBREW_PREFIX/bin/bash >> /etc/shells"
execute chsh -s "$HOMEBREW_PREFIX/bin/bash"
