#! /usr/bin/env bash
eval "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
execute_sudo sh -c "echo $HOMEBREW_PREFIX/bin > /etc/paths.d/homebrew"
eval "$($HOMEBREW_PREFIX/bin/brew shellenv)"
curl -fsSL https://raw.githubusercontent.com/xko/bush/mac/.bush/Brewfile brew | bundle -q --file=- --no-lock